[tool.black]
line-length = 100
target-version = ["py312"]
exclude = """
/(
    \\.git
  | __pycache__
  | \\.venv
)/
"""

[tool.ruff]
line-length = 100
target-version = "py312"
extend-exclude = [".venv"]

[tool.ruff.lint]
select = ["E", "F", "W", "B", "Q"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
