"""Project-wide constants for configurable defaults."""

ACTIVATION_ATTEMPT_LIMIT = 5
ACTIVATION_ATTEMPT_WINDOW_SECONDS = 5 * 60
ACTIVATION_LOCK_SECONDS = 15 * 60

RESEND_PER_MINUTE_LIMIT = 1
RESEND_MINUTE_WINDOW_SECONDS = 60
RESEND_DAILY_LIMIT = 5
RESEND_DAILY_WINDOW_SECONDS = 24 * 60 * 60

__all__ = [
    "ACTIVATION_ATTEMPT_LIMIT",
    "ACTIVATION_ATTEMPT_WINDOW_SECONDS",
    "ACTIVATION_LOCK_SECONDS",
    "RESEND_PER_MINUTE_LIMIT",
    "RESEND_MINUTE_WINDOW_SECONDS",
    "RESEND_DAILY_LIMIT",
    "RESEND_DAILY_WINDOW_SECONDS",
]
